### ISSUE TITLE
Instance is not always intersected with motion bvh, multiple transformations and rtcIntersect1M

### ISSUE THREAD

**Issue by pborsutzki** [embree/embree#352] opened 2021-12-14 17:19 UTC
Hi,

I stumbled upon a situation where embree fails to intersect an instance with 3 transformations where one contains a quaternion rotation. The key to reproducing the problem seem to be incoherent ray times in combination with `rtcIntersect1M`. Increasing the number of incoherent ray times that are given to `rtcIntersect1M` seems to make it less likely that the instance is intersected in this situation. I so far could not reproduce the issue with just 2 transformations.

I modified the quaternion motion blur tutorial to reproduce the problem, find [the patch based on Embree 3.13.2 attached](https://github.com/embree/embree/files/7713457/embree_motionblur_problem_2.zip). The sample is preconfigured to show the problem by toggling the "incoherent ray time" switch. You should notice a brightness  difference and a difference in the length of the area where the cube is blurred.

In a RelWithDebInfo build an assertion was triggered pointing [here](https://github.com/embree/embree/blob/d7157470e089098b9c7323f608835ed50453e606/kernels/bvh/bvh_intersector_hybrid.cpp#L120), though I am not sure which one it was exactly.

Thanks for having a look into this!

**Comment by freibold** [comment] 2021-12-16 14:23
Hi again =)

I can't reproduce this issue on my side. If I understood you correctly, the images rendered with g_incoherent_ray_time = true and g_incoherent_ray_time = false should differ in your example without changing any other setting, correct? When I'm trying this, the images rendered with 512 spp (i.e ./quaternion_motion_blur -spp 512 -o image.tga) are visually identical. I also don't get any assertions.

Can you double check and verify that your patch applied to an unmodified Embree version has the described issue? If that's the case there might be something more subtle going on.

Can you tell me which OS and compiler you are using? Can you provide the output of 

./quaternion_motion_blur --verbose 2

and maybe share the content of your CMakeCache.txt? Feel free to DM me at florian.reibold@intel.com

Cheers

**Comment by freibold** [comment] 2021-12-16 15:13
Can you also try to set [ENABLE_FAST_COHERENT_CODEPATHS](https://github.com/embree/embree/blob/d7157470e089098b9c7323f608835ed50453e606/kernels/bvh/bvh_intersector_hybrid.cpp#L30) to 0 and recompile to check if the problem is still there?

**Comment by freibold** [comment] 2022-01-28 17:43
Issue is fixed (confirmed via DM) and the fix will be included in the next embree release.

**Closed by freibold** 2022-01-28 17:43 UTC
