### ISSUE TITLE
Avoid intersection with some ID of primitive

### ISSUE THREAD

**Issue by rperrot** [embree/embree#92] opened 2016-07-20 15:47 UTC
The question : Is there a way in embree to avoid intersection with a specified ID or IDs of primitive ? 

The details : I'm trying to replace my own QBVH with embree, but I can't reproduce some of my specification. My scenes are only composed of triangles so a ray could not intersect two times the same triangle. That means that for a shadow ray, the triangle to be lit should be removed or deactivated during ray queries. The same computation could also be done for path tracing (the last triangle ID should be deactivated). With that purpose, tidy epsilon management is fully removed. 

I'm trying to see if this is possible in embree. I though I could use rtcEnable but this function enable or disable a full geometry (and my scene is considered as a single geometry object). A good thing would be to have a rtcEnable that can go a step further (enable/disable a primitiveID of a geometryID) 

So I'm stuck and no idea how to implement it in embree (simply I mean). I still didn't look too much at the architecture of the code. 

Anybody have a suggestion if it is possible to do this with embree (and If so, how to do it ?) ?

Thank in advance !

**Comment by johguenther** [comment] 2016-07-26 12:08
You could use Embree's intersection filter feature (`rtcSetIntersectionFilterFunction*` and `rtcSetOcclusionFilterFunction*`) to reject hits based on the last hit primitive ID, which you additionally attach to each ray. See [`tutorials/intersection_filter`](https://github.com/embree/embree/blob/master/tutorials/intersection_filter/intersection_filter_device.cpp) for an example how to implement this.

Please not that the approach to avoid self-intersections based on primitive IDs does not work in general, because it assumes that no geometry is overlapping. However, it looks like you can guarantee this for your scenes.

**Comment by rperrot** [comment] 2016-07-26 14:10
Thanks for your answer. 

I know overlapping is in issue, but this is mainly caused by incorrect topology on the scene and it does not happened (I got filtering approach that removes inconsistent scenes). Epsilon approach could also lead to some missing intersection, there are drawbacks on both approach. 

I already saw the filtering approach but as far as I known it's triggered after scene intersection, however I want it during intersection to avoid incorrect match and keep intersecting with the remaining objects/triangles of the scene. If I detect a self intersection I can't say that there exists (or not) any remaining intersection with the other objets. 

I don't know if my details are clear enough, please ask me if you want more details.

**Comment by johguenther** [comment] 2016-07-26 15:18
The filter functions are applied *during* ray intersection, for each potential hit, not just afterwards when the closest hit was found. It should be the solution you are looking for.

**Comment by rperrot** [comment] 2016-07-26 15:21
Oh yes !!! It's wonderful !

Thank you so much for your answer and more generally with the wonderful library !

**Comment by cbenthin** [comment] 2016-08-02 08:06
Seems like the issue is solved. Closing it for now.

**Closed by cbenthin** 2016-08-02 08:06 UTC
