### ISSUE TITLE
Issue with intersectNodeMB4D for AVX2

### ISSUE THREAD

**Issue by maikschulze** [embree/embree#300] opened 2020-08-14 07:27 UTC
I have discovered an issue with the motion_blur_geometry tutorial in AVX2 mode.

I can consistently reproduce the problem with the following setup:
Embree Version: v3.11.0
OS: Windows 10
Compiler: MSVC 19.27.29110, Debug configuration
Executable: motion_blur_geometry
Arguments: --isa avx2

For example, the following ray added to **renderFrameStandard** will trigger the assert during intersection:

```
extern "C" void renderFrameStandard (int* pixels,
                          const unsigned int width,
                          const unsigned int height,
                          const float time,
                          const ISPCCamera& camera)
{
  Vec3fa color = renderPixel(data,(float)(504),(float)(504),camera,g_stats[0]);
  ..
}
```

From my understanding the issue is caused by improper nan propagation of the second AVX2-specific code block in function **intersectNodeMB4D**:

```
#if defined(__AVX2__) && !defined(__AVX512F__)
      const vfloat<N> tNear = maxi(maxi(tNearX,tNearY),maxi(tNearZ,ray.tnear));
      const vfloat<N> tFar  = mini(mini(tFarX ,tFarY ),mini(tFarZ ,ray.tfar ));
#else
      const vfloat<N> tNear = max(ray.tnear,tNearX,tNearY,tNearZ);
      const vfloat<N> tFar  = min(ray.tfar, tFarX ,tFarY ,tFarZ );
#endif
```
For the following variables:
```
tNearX = {v={m256_f32=0x000000d010bdbf80 {13.8293447, 7.54327869, nan, nan, nan, nan, nan, nan} } f=0x000000d010bdbf80 {...} ...}
tNearY = {v={m256_f32=0x000000d010bdbf60 {54.2472305, 54.2472305, nan, nan, nan, nan, nan, nan} } f=0x000000d010bdbf60 {...} ...}
tNearZ = {v={m256_f32=0x000000d010bdbf40 {-14.8824348, -14.8824348, nan, nan, nan, nan, nan, nan} } f=0x000000d010bdbf40 {...} ...}
tFarX = {v={m256_f32=0x000000d010bdbfe0 {16.3437767, 10.0577068, nan, nan, nan, nan, nan, nan} } f=0x000000d010bdbfe0 {...} ...}
tFarY = {v={m256_f32=0x000000d010bdbfc0 {64.1103668, 64.1103668, nan, nan, nan, nan, nan, nan} } f=0x000000d010bdbfc0 {...} ...}
tFarZ = {v={m256_f32=0x000000d010bdbfa0 {-11.3806705, -11.3806705, nan, nan, nan, nan, nan, nan} } f=0x000000d010bdbfa0 {...} ...}
```

the AVX2 code yields:
```
tNear = {v={m256_f32=0x000000d010bdbe60 {54.2472305, 54.2472305, 0.000000000, 0.000000000, 0.000000000, 0.000000000, ...} } ...}
tFar = {v={m256_f32=0x000000d010bdc000 {-11.3806705, -11.3806705, inf, inf, inf, inf, inf, inf} } f=0x000000d010bdc000 {...} ...}
vmask = {v={m256_f32=0x0000004f6ad8c020 {0.000000000, 0.000000000, -nan, -nan, -nan, -nan, -nan, -nan} } vl=...}
mask = 252
dist = {v={m256_f32=0x000000d010bdc3a0 {54.2472305, 54.2472305, 0.000000000, 0.000000000, 0.000000000, 0.000000000, ...} } ...}
```

whereas, the non-AVX2 block yields:
```
tNear = {v={m256_f32=0x000000179817c1e0 {54.2472305, 54.2472305, nan, nan, nan, nan, nan, nan} } f=0x000000179817c1e0 {...} ...}
tFar = {v={m256_f32=0x000000179817c380 {-11.3806705, -11.3806705, nan, nan, nan, nan, nan, nan} } f=0x000000179817c380 {...} ...}
vmask = {v={m256_f32=0x000000de1c11bce0 {0.000000000, 0.000000000, 0.000000000, 0.000000000, 0.000000000, 0.000000000, ...} } ...}
mask = 0
dist = {v={m256_f32=0x000000179817c6a0 {54.2472305, 54.2472305, nan, nan, nan, nan, nan, nan} } f=0x000000179817c6a0 {...} ...}
```

This leads to improper entry of the function **traverseClosestHit** in AVX2:

![image](https://user-images.githubusercontent.com/4232812/90224276-b58cca00-de0f-11ea-88df-28f21b35644c.png)

The problem can be easily worked around by avoiding the usage of **mini/maxi** in **intersectNodeMB4D**. I'm unsure whether there are further node intersection functions that could cause similar problems.

**Comment by cbenthin** [comment] 2020-08-14 13:17
Hi Maik,

thanks for reporting this. I cannot reproduce this on Linux and it seems there's some code generation issue with MSVC on windows in debug mode. The following in AVX2 mode:
tNear = {v={m256_f32=0x000000d010bdbe60 {54.2472305, 54.2472305, 0.000000000, 0.000000000, 0.000000000, 0.000000000, ...} } ...}
should not be. The  0.000000000s in the invalid lanes are wrong because if you do an integer max on NANs (7FBFFFFF) to compute tNear you can never get 0.

I'll need to test on windows. Which version of Visual Studio are you using exactly?

**Comment by maikschulze** [comment] 2020-08-14 14:47
Hi Carsten,

I'm using the currently recent version of Microsoft Visual Studio Professional 2019, Version 16.7.1.

I will have a look at the behavior in clang-cl next week and report my findings.

**Comment by cbenthin** [comment] 2020-08-14 19:10
OK, I can reproduce it on windows with VS19 in Debug mode. In release mode everything works fine so its very likely a code generation issue in DEBUG mode. Will have a closer look at the ASM code next week.

**Comment by cbenthin** [comment] 2020-08-14 20:31
OK, I digged a little deeper and it seems we run into a compile issue in DEBUG mode where MSVC does not set the __AVX2__ define anymore for whatever reason. Therefore the wrong version of maxi() for AVX2 is compiled in DEBUG mode. It seems other folks run into something related as well:
https://stackoverflow.com/questions/54114287/visual-studio-not-recognizing-avx2-or-avx

It seems something new with VS2019. Will try to find a workaround if possible.

**Comment by maikschulze** [comment] 2020-08-17 14:03
Hi Carsten,

thank you for looking into this so quickly! According to my test, the issue does also not appear when compiling with "ClangCL" in Visual Studio 2019. I see no problems in Release or Debug mode, even with different levels of inlining the affected functions. I just had to slightly adjust msvc.cmake to support this compiler:

```
..
SET(FLAGS_SSE42 "${FLAGS_SSE2} /D__SSE3__ /D__SSSE3__ /D__SSE4_1__ /D__SSE4_2__")
IF (${CMAKE_GENERATOR_TOOLSET} MATCHES "^ClangCL")
  SET(FLAGS_SSE42 "${FLAGS_SSE42} /clang:-msse4.2") # ClangCL does not seem to consume /D__SSE4_2__.
ENDIF()
SET(FLAGS_AVX   "${FLAGS_SSE42} /arch:AVX")
..
```

**Comment by cbenthin** [comment] 2020-08-17 14:36
Hi,

I've spent some time on it today but MSVC behaves very weird, as I cannot get it to generate the __AVX2__ preprocessor macro even though I've enabled /arch:AVX2 etc. Right now the recommended workaround is to disable AVX2 support in DEBUG mode or as you did use another compiler like clang or the intel compiler.

**Comment by cbenthin** [comment] 2020-08-17 19:47
As I cannot get MSVC to behave nicely here's a simpler workaround to still use MSVC in DEBUG mode.
In vfloat8_avx.h please replace lines 349-355:

__forceinline vfloat8 mini(const vfloat8& a, const vfloat8& b) {
    return min(a,b);
  }

  __forceinline vfloat8 maxi(const vfloat8& a, const vfloat8& b) {
    return max(a,b);
  }

by 

__forceinline vfloat8 mini(const vfloat8& a, const vfloat8& b) {
    return asFloat(min(asInt(a),asInt(b)));
  }

  __forceinline vfloat8 maxi(const vfloat8& a, const vfloat8& b) {
    return asFloat(max(asInt(a),asInt(b)));
  }

That should at least ensure correct behavior when MSVC fails to produce correct AVX2 code and falls back to AVX code for maxi/mini.

**Comment by maikschulze** [comment] 2020-08-18 05:36
Thank You Carsten, this works.

**Comment by cbenthin** [comment] 2020-08-18 06:32
Ok, great. With a working workaround for this MSVC bug I'll closing the issue. Please reopen if you run into more issues in debug mode.

**Closed by cbenthin** 2020-08-18 06:32 UTC

**Comment by maikschulze** [comment] 2020-08-18 09:51
I tested a bit more, but could not resolve the problem. The issue seems to only occur with /Ob0. I cannot see any problem with the pre-processed files /P for the respective intersector classes, or rather any difference between them in debug in release. Both pre-processed files contain the correct AVX2 version of mini/maxi.

I would therefore imagine it's related to how MSVC links the libraries together, since __forceinline does not inline with /Ob0 according to https://docs.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=vs-2019

**Comment by cbenthin** [comment] 2020-08-18 09:58
Yes, MSVC seems to link against the AVX version of maxi/mini instead of the AVX2 version. I guess MSVC just picks up the first available and does not recognize that multiple version compiled for different ISAs exists.

Just to double-check: The workaround from yesterday works on your side, as your last post mentions that "you could not resolve the problem".

**Comment by maikschulze** [comment] 2020-08-18 10:01
Yes, I have the same assumption about the linking behavior.

Your workaround works for me, yes. The behavior (of the wrongly selected) mini/maxi functions are stabilized this way. Thanks!

**Comment by maikschulze** [comment] 2020-08-18 10:20
I've found an interesting article about what might be going on:
https://randomascii.wordpress.com/2016/12/05/vc-archavx-option-unsafe-at-any-speed/

I have quickly realized one of its suggestions and marked the respective functions "static", e.g.
static __forceinline vfloat8 mini(const vfloat8& a, const vfloat8& b)

Gladly, this seems to address the issue. Could this be put into the codebase or would side effects be problematic?

**Comment by cbenthin** [comment] 2020-08-19 10:00
Good catch. I've replaced "__forceinline" by "static __forceinline" in the codebase. So far I don't observed any side effects so this should be in the next official release.

**Comment by maikschulze** [comment] 2020-08-19 10:15
Wonderful! Thank you very much, Carsten.
