### ISSUE TITLE
Embree doesn't build with Cray Programming Environment

### ISSUE THREAD

**Issue by chuckatkins** [embree/embree#118] opened 2017-03-23 11:54 UTC
Related: ospray/ospray#132

This is basically the same problem as #115.  The compilers used in a Cray environment are wrappers around the underlying compiler driver that pass an extensive set of additional flags based on currently loaded environment modules.  Think something similar to mpicc; i.e. if you have the cray-mpich module loaded, it adds additional include and linker flags to use mpi, if you have cray-libsci loaded, then it adds extra flags to use the Cray accelerated math libraries, etc.  This is also how the compiler target architecture is specified.  So, if I have the Cray Intel environment loaded with the craype-mic-knl modules, then under the hood it actually calls icc -xmic-avx512,  Similary, if the craype-haswell module is loaded then -xCORE-AVX2 is actually being used.

The problem with the approach taken to resolve #115 is that in a Cray environment, target ISA options are not handled through compiler flags, so from the build system point of view you don't know what flags are getting passed to the underlying compiler driver.  The best you could really do would be a series of try_compile to test if the various ISAs were supported. The whole premise of adding different compiler flags to build with a different ISA doesn't really work in the Cray environment since to build for a different target ISA you actually need to swap an environment module from the shell.  You can also test for this in newer versions of CMake (i.e >= 3.5) with ```if( CMAKE_<lang>_COMPILER_WRAPPER STREQUAL "CrayPrgEnv")```

**Comment by cbenthin** [comment] 2017-03-23 12:38
Hi,

could you give the just released Embree 2.15 a try, as we ignoring compiler flags per default in this version.
Thanks.

**Comment by chuckatkins** [comment] 2017-03-23 13:46
I did, same result.  As I mentioned, when using the Cray environment, there are no compiler flags visible to the build system since they're all handled internally by the wrappers.  You would get a similar effect if you created shell scripts iccavx2 and icpcavx2:
```bash
#!/bin/bash
icc -xCORE-AVX2 "$@"
```
```bash
#!/bin/bash
icpc -xCORE-AVX2 "$@"
```
and then configured with CC=iccavx2 and CXX=icpcavx2.  From here you can see the -xCORE-AVX2 flag is entirely opaque and unknown to cmake.  That's essentially how the Cray Programming environment works.

**Comment by johguenther** [comment] 2017-03-23 13:55
Is it possible to load the module `craype-target-native` when compiling Embree? This prevents CPE to add compiler flags but still ensures linking to the correct libraries.

**Comment by chuckatkins** [comment] 2017-03-23 14:03
No.  It's a deprecated module from a much older version of CPE and not really supported or even available anymore.  You pretty much always need to use an architecture-specific module now.  If you can make the build work correctly with dummy wrappers I described above then it should work with the Cray Programming Environment.

**Comment by svenwoop** [comment] 2017-03-23 14:07
A possible solution would be to configure Embree with the exact same ISA as your compile flags force the compilation to. This does not yet work properly with current Embree, but will look into this tomorrow. Is this a solution that would work for you? It would just require to configure Embree to the ISA you configured your compilation environment to.

**Comment by chuckatkins** [comment] 2017-03-23 14:13
Yes, that would be doable.  It should also be easy enough to determine automatically with a few try_compile tests, although explicitly would be fine too.

**Comment by svenwoop** [comment] 2017-03-24 09:43
Could you please try if the issue is fixed with v2.16.0-alpha.0? Just set EMBREE_MAX_ISA to NONE, and enable the single EMBREE_ISA_XXX that your environment is configured to. You also have to enable only that one ISA in Ospray, as you otherwise get ISPC related link issues.

**Closed by svenwoop** 2017-03-24 09:43 UTC

**Comment by chuckatkins** [comment] 2017-03-25 03:27
This works now, btw, so thank you.  With the two new PRs #119 and #120 building with the Cray PE yields much better results.

**Comment by svenwoop** [comment] 2017-03-27 05:40
Please send us an ICLA (https://embree.github.io/data/Embree-ICLA.pdf) and CLA (https://embree.github.io/data/Embree-CCLA.pdf) then we can merge these changes.
