### ISSUE TITLE
rtcOccludedN issue

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [embree/embree#74] opened 2016-05-02 14:56 UTC
Hi,

I was trying to play with functions rtcIntersectN and rtcOccludedN but I get strange behavior with the second one. My test is as follow, I just adapted the tutorial "triangle_geometry" to use ray paquets instead of individual ray intersection. My "renderTile" function then becomes:

```cpp
/* task that renders a single screen tile */
void renderTile(int taskIndex, int* pixels,
    const int width,
    const int height,
    const float time,
    const Vec3fa& vx,
    const Vec3fa& vy,
    const Vec3fa& vz,
    const Vec3fa& p,
    const int numTilesX,
    const int numTilesY)
{
    const int tileY = taskIndex / numTilesX;
    const int tileX = taskIndex - tileY * numTilesX;
    const int x0 = tileX * TILE_SIZE_X;
    const int x1 = min(x0 + TILE_SIZE_X, width);
    const int y0 = tileY * TILE_SIZE_Y;
    const int y1 = min(y0 + TILE_SIZE_Y, height);

    const auto tileSize = TILE_SIZE_X * TILE_SIZE_Y;
    RTCRay rays[tileSize];

    processTile(x0, y0, [&](int idx, int i, int j, int x, int y) {
        /* initialize ray */
        auto& ray = rays[idx];
        ray.org = p;
        ray.dir = normalize(x*vx + y*vy + vz);
        ray.tnear = 0.0f;
        ray.tfar = inf;
        ray.geomID = RTC_INVALID_GEOMETRY_ID;
        ray.primID = RTC_INVALID_GEOMETRY_ID;
        ray.mask = -1;
        ray.time = 0;
    });

    rtcIntersectN(g_scene, &rays[0], tileSize, sizeof(RTCRay));

    RTCRay shadows[tileSize];

    const Vec3fa lightDir = normalize(Vec3fa(-1, -1, -1));

    processTile(x0, y0, [&](int idx, int i, int j, int x, int y) {
        /* initialize shadow ray */
        const auto& ray = rays[idx];
        auto& shadow = shadows[idx];
        shadow.org = ray.org + ray.tfar*ray.dir;
        shadow.dir = neg(lightDir);
        shadow.tnear = 0.001f;
        shadow.tfar = (ray.geomID != RTC_INVALID_GEOMETRY_ID) ? inf : -1.f; // Embree API doc:  Regardless of the input layout a single ray in a ray stream is considered inactive during traversal/intersection if its tnear value is larger than its tfar value.
        shadow.geomID = RTC_INVALID_GEOMETRY_ID;
        shadow.primID = RTC_INVALID_GEOMETRY_ID;
        shadow.mask = 1;
        shadow.time = 0;
    });

    rtcOccludedN(g_scene, &shadows[0], tileSize, sizeof(RTCRay));

    processTile(x0, y0, [&](int idx, int i, int j, int x, int y) {
        const auto& ray = rays[idx];
        /* calculate pixel color */
        Vec3fa diffuse = face_colors[ray.primID];
        Vec3fa color = diffuse*0.5f;

        const auto& shadow = shadows[idx];

        /* add light contribution */
        if (shadow.tnear < shadow.tfar && shadow.geomID)
            color = color + diffuse*clamp(-dot(lightDir, normalize(ray.Ng)), 0.0f, 1.0f);

        /* write color to framebuffer */
        unsigned int r = (unsigned int)(255.0f * clamp(color.x, 0.0f, 1.0f));
        unsigned int g = (unsigned int)(255.0f * clamp(color.y, 0.0f, 1.0f));
        unsigned int b = (unsigned int)(255.0f * clamp(color.z, 0.0f, 1.0f));
        pixels[y*width + x] = (b << 16) + (g << 8) + r;
    });
}

/* simple helper to loop over a tile */
template<typename Functor>
void processTile(int x0, int y0, Functor&& f) {
    for (auto j = 0; j < TILE_SIZE_Y; ++j) {
        for (auto i = 0; i < TILE_SIZE_X; ++i) {
            f(j * TILE_SIZE_X + i, i, j, x0 + i, y0 + j);
        }
    }
}
```

When I run this under Visual Studio 2015 in debug mode (Win64) I trigger the assert line 457 of bvh_intersector_stream.cpp:

`assert(__popcnt(m_trav_active) <= 32);`

Note that if I replace the call to rtcOccludedN by a loop over each shadow ray, everything works fine:

``` cpp
for (auto i = 0; i < tileSize; ++i) {
        rtcOccludedN(g_scene, &shadows[i], 1, sizeof(RTCRay));
    }
```

I can even trace shadow rays in paquets, but with less rays in a batch. For example, the following loop works fine:

 ``` cpp
for (auto i = 0; i < tileSize; i += TILE_SIZE_X) {
        rtcOccludedN(g_scene, &shadows[i], TILE_SIZE_X, sizeof(RTCRay));
    }
```

So it seems the problem is related to the number of rays I am trying to pass to rtcOccludedN.

I must admit that I did not investigate very far the purpose of the variable "m_trav_active" in bvh_intersector_stream.cpp and why its number of bits set to "1" exceeds 32 at some point.

PS: Some more details about my compilation options:
RTCORE_BACKFACE_CULLING = 0
RTCORE_BUFFER_STRIDE = 1
RTCORE_ENABLE_RAYSTREAM_LOGGER = 0
RTCORE_EXPORT_ALL_SYMBOLS = 0
RTCORE_IGNORE_INVALID_RAYS = 1
RTCORE_INTERSECTION_FILTER = 1
RTCORE_INTERSECTION_FILTER_RESTORE = 1
RTCORE_MEMKIND_ALLOCATOR = 0
RTCORE_RAY_MASK = 1
RTCORE_RAY_PACKETS = 1
RTCORE_STAT_COUNTERS = 0
RTCORE_STAT_COUNTERS = INTERNAL

**Comment by cbenthin** [comment] 2016-05-02 15:37
Seems to be that disabling of shadows rays (for primary rays which didn't hit anything) is causing the issue here. I'll try to reproduce your issue to see what is going wrong exactly.
As a workaround you could also try to densely fill your "shadows" structure so that all rays within are valid.

For Embree 2.9 there's also some example code for using streams in view_device.cpp and tutorial_device.cpp. More sophisticated examples and support for ray streams is coming in next Embree release.

Thanks,
Carsten

**Comment by Celeborn2BeAlive** [comment] 2016-05-02 15:59
Thanks for the answer,

I've tried packing and sending only valid shadow rays but still get the same issue, here is the code:

```cpp
/* task that renders a single screen tile */
void renderTile(int taskIndex, int* pixels,
    const int width,
    const int height,
    const float time,
    const Vec3fa& vx,
    const Vec3fa& vy,
    const Vec3fa& vz,
    const Vec3fa& p,
    const int numTilesX,
    const int numTilesY)
{
    const int tileY = taskIndex / numTilesX;
    const int tileX = taskIndex - tileY * numTilesX;
    const int x0 = tileX * TILE_SIZE_X;
    const int x1 = min(x0 + TILE_SIZE_X, width);
    const int y0 = tileY * TILE_SIZE_Y;
    const int y1 = min(y0 + TILE_SIZE_Y, height);

    const auto tileSize = TILE_SIZE_X * TILE_SIZE_Y;
    RTCRay rays[tileSize];

    processTile(x0, y0, [&](int idx, int i, int j, int x, int y) {
        /* initialize ray */
        auto& ray = rays[idx];
        ray.org = p;
        ray.dir = normalize(x*vx + y*vy + vz);
        ray.tnear = 0.0f;
        ray.tfar = inf;
        ray.geomID = RTC_INVALID_GEOMETRY_ID;
        ray.primID = RTC_INVALID_GEOMETRY_ID;
        ray.mask = -1;
        ray.time = 0;
    });

    rtcIntersectN(g_scene, &rays[0], tileSize, sizeof(RTCRay));

    RTCRay shadows[tileSize];

    const Vec3fa lightDir = normalize(Vec3fa(-1, -1, -1));

    size_t shadow_ray_count = 0;
    processTile(x0, y0, [&](int idx, int i, int j, int x, int y) {
        /* initialize shadow ray */
        const auto& ray = rays[idx];

        if (ray.geomID != RTC_INVALID_GEOMETRY_ID) {
            auto& shadow = shadows[shadow_ray_count++];
            shadow.org = ray.org + ray.tfar*ray.dir;
            shadow.dir = neg(lightDir);
            shadow.tnear = 0.001f;
            shadow.tfar = inf;
            shadow.geomID = RTC_INVALID_GEOMETRY_ID;
            shadow.primID = RTC_INVALID_GEOMETRY_ID;
            shadow.mask = 1;
            shadow.time = 0;
        }
    });

    if (shadow_ray_count) {
        rtcOccludedN(g_scene, &shadows[0], shadow_ray_count, sizeof(RTCRay));
    }

    shadow_ray_count = 0;
    processTile(x0, y0, [&](int idx, int i, int j, int x, int y) {
        const auto& ray = rays[idx];
        Vec3fa color = Vec3fa(0);

        if (ray.geomID != RTC_INVALID_GEOMETRY_ID) {
            /* calculate pixel color */
            Vec3fa diffuse = face_colors[ray.primID];
            color = diffuse*0.5f;

            const auto& shadow = shadows[shadow_ray_count++];

            /* add light contribution */
            if (shadow.tnear < shadow.tfar && shadow.geomID)
                color = color + diffuse*clamp(-dot(lightDir, normalize(ray.Ng)), 0.0f, 1.0f);
        }
        /* write color to framebuffer */
        unsigned int r = (unsigned int)(255.0f * clamp(color.x, 0.0f, 1.0f));
        unsigned int g = (unsigned int)(255.0f * clamp(color.y, 0.0f, 1.0f));
        unsigned int b = (unsigned int)(255.0f * clamp(color.z, 0.0f, 1.0f));
        pixels[y*width + x] = (b << 16) + (g << 8) + r;
    });
}
```

**Comment by Celeborn2BeAlive** [comment] 2016-05-02 16:11
I've just tried the viewer tutorial with the ambient occlusion pass, which makes use of rtcOccludedN. 

While it does not produce an error when the direction is chosen randomly, I hit the "assert" if I set a constant direction for all occlusion rays. That is, by replacing (line 290):

```cpp
      const float oneOver10000f = 1.f/10000.f;
      seed = 1103515245 * seed + 12345;
      dir.x = (seed%10000)*oneOver10000f;
      seed = 1103515245 * seed + 12345;
      dir.y = (seed%10000)*oneOver10000f;
      seed = 1103515245 * seed + 12345;
      dir.z = (seed%10000)*oneOver10000f;
```

with:

```cpp
     dir = normalize(Vec3fa(1, 1, 1));
```

**Comment by cbenthin** [comment] 2016-05-02 16:48
OK, so from a brief investigation it seems that the "assert" is simply wrong. Could you either remove it or replace it by something like "if (cur != BVH::invalidNode) assert(__popcnt(m_trav_active)<=32);" and check whether your app/code works as expected. Thanks.

**Comment by Celeborn2BeAlive** [comment] 2016-05-02 19:12
Removing the assert allows the modified tutorial to work correctly; However, I will not be able to experiment rtcOccludedN on a larger code base until some time :s

**Comment by cbenthin** [comment] 2016-05-26 07:53
OK, I'll close this issue for now as it seems to be fixed. Reopen if it comes up again.

**Closed by cbenthin** 2016-05-26 07:53 UTC
