### ISSUE TITLE
checking if a line segment is fully out side the mesh except the two start/end points that lie on the mesh

### ISSUE THREAD

**Issue by etrigger** [embree/embree#132] opened 2017-06-16 09:30 UTC
For a given mesh, I need to connect any two vertices of the mesh which forms a line segment. I then want to check if this line segment penetrates the internal area inside the mesh(or in other ways, I want to check if this line segment is completely outside the shape except for the two end points lying on the surface of the mesh).

Here is one example:
The vertex index stars from 0. The index for vertex A and B is 2857 and 5468, respectively.
The green triangle face is the first hit face.

When the ray shoots from B to A, the first hit is the face containing B;
When the ray shoots from A to B, the first hit is the face containing A;
For the ray shooting from B to A, I move the point B along the normalized direction of vector B->A, it does not hit anything;
Similarly, for the ray shooting from A to B, I move the point A along the normalized direction of vector A->B, it does not hit anything;
But, if I scale the normalized vector a little bit, e.g. multiply by 0.1, and then add it to the source vertex, I can get two hits.

![raytracing1](https://user-images.githubusercontent.com/3329503/27219954-b88d6a2c-5283-11e7-9cdb-05d5422df4d7.jpg)
![raytracing2](https://user-images.githubusercontent.com/3329503/27219955-bab78fc6-5283-11e7-9345-0f24cce920b7.jpg)

However,  as shown below, sometimes the first hit is not necessarily the starting point.
![raytracing3](https://user-images.githubusercontent.com/3329503/27220792-ad441ca8-5286-11e7-93f1-47ad1e3eecb4.jpg)

I am confused because the first hit sometimes happens on the starting point and sometimes not.
I want to use the number of hits to determine if a line segment penetrates a mesh or not. But it sees the number of hits may not be  very stable.

Any suggestions would be thankful.

Here is the obj file. Frame 3 for the first and second picture, and Frame 0 for the last picture.
[02-05-manifold.zip](https://github.com/embree/embree/files/1080420/02-05-manifold.zip)

**Comment by svenwoop** [comment] 2017-06-19 04:54
If you just trace a line from vertex A to vertex B you might miss intersections at A and B. That is to be expected due to numerical issues. To fix this you can move your start point a little inside the mesh, e.g. start at A+eps*normalize(A-B) where eps should be small (e.g. 1E-5).

You seem to do the same, but with a very large epsilon. This is why you hit a vertex far behind the start point.

**Comment by cbenthin** [comment] 2017-08-28 12:53
I'll close this issue for now, please re-open if the issue is still relevant.

**Closed by cbenthin** 2017-08-28 12:53 UTC
