### ISSUE TITLE
Out of bounds primitive split

### ISSUE THREAD

**Issue by Hengoo** [embree/embree#328] opened 2021-07-16 12:46 UTC
I have some issues with primitive Splitting and the BVH builder that is exposed with rtcBuildBVH. (https://github.com/embree/embree#rtcbuildbvh)

Embree sometimes calls the splitPrimitive function with a position that is exactly on, or even outside of the primitive bounds. I think both cases make no sense and should be catched before the split primitive function is called.

The first case, a split value that is on the bounds can be be observed with the tutorial.
Add
```C++
    if (((&prim->lower_x)[dim] == pos) ||
      ((&prim->upper_x)[dim] == pos)) {
      // Split position is exactly on the bounds of the primitive
      // This case also happens with the random triangles from the example
      std::cout << "Split on the bounds with pos = " << pos << " and lower Bounds: " << (&prim->lower_x)[dim] << ", upper Bounds: " << (&prim->upper_x)[dim] << std::endl;
      //assert(false);
    }
```
To https://github.com/embree/embree/blob/master/tutorials/bvh_builder/bvh_builder_device.cpp#L23

For the second case I can also reproduce it with the Tutorial builder
 by loading some custom primitives and adding this code to the splitTriangle function:
```C++
    if (((&prim->lower_x)[dim] > pos) ||
      ((&prim->upper_x)[dim] < pos)) {
      // The split position is outside of the primitive bounds.
      // This only happens with the primitiveDump
      std::cout << "Out of bounds split with pos = " << pos << " and lower Bounds: " << (&prim->lower_x)[dim] << ", upper Bounds: " << (&prim->upper_x)[dim] << std::endl;
      //assert(false);
    }
```

To load the primitives: [primitiveTest.txt](https://github.com/embree/embree/files/6830633/primitiveTest.txt) replace the random bounding box generation https://github.com/embree/embree/blob/master/tutorials/bvh_builder/bvh_builder_device.cpp#L144 with:
```C++
      // Load primitives:
      std::vector<RTCBuildPrimitive> primitives;
      primitives.resize(528);
      std::ifstream file;
      file.open("primitiveTest", std::ofstream::in | std::ofstream::binary);
      file.read(reinterpret_cast<char*>(primitives.data()), primitives.size() * sizeof(int));
      file.close();

      const size_t N = 528;
      const size_t extraSpace = 1072 - 528;
      avector<RTCBuildPrimitive> prims;
      prims.resize(N);
      for (size_t i = 0; i < N; i++)
      {
        prims[i] = primitives[i];
      }
```
and place the file in the build folder (tutorials\bvh_builder)

And a bit related, what should we do in the splitPrimitive function when we know that the primitive should not be split? Create infinite bounding box? Very large bounding box? NaN?
I would need this to avoid the out of bounds splits. And an other case is when I want to build a BVH that contains different primitives, where some for primitives should never be split. Like instances, or other thing that are extremely expensive and we never want to visit twice during traversal.

**Comment by svenwoop** [comment] 2021-09-27 05:53
Could you please try out of branch issue_328_out_of_bounds_spatial_split fixes your issue.

**Comment by svenwoop** [comment] 2021-09-27 06:53
If you want a primitive to not get spatially split, then just return empty bounds (inf,-inf) for the left bounds, and return primitive bounds in right bounds.

**Comment by Hengoo** [comment] 2021-09-30 12:21
The out ouf bounds split issue seem to be fixed, but there is still an other problem that causes Embree call the `setBounds` function with empty bounds (inf, -inf) for the second child. (only when triangle splitting is enabled)

You can reproduce it with the BVH build example. 
[Example.zip](https://github.com/embree/embree/files/7259168/Example.zip)
The zip contains a `bvh_builder_device.cpp` that you can copy over the existing one (https://github.com/embree/embree/blob/master/tutorials/bvh_builder/bvh_builder_device.cpp) and the file called `primitiveTest_6085` needs to be in the build folder under `tutorials\bvh_builder`.

When you start the bvh build project it will crash at the assertions in `SetBounds`. (when you remove those it will hit the assert in `Node::Create` function that makes sure that numPrims == 1)

**Comment by svenwoop** [comment] 2021-10-06 10:21
Could you please try the issue_328_out_of_bounds_spatial_split branch again. Think the issue is fixed now.

**Comment by svenwoop** [comment] 2021-10-13 05:26
This fix will be in the next release.

**Closed by svenwoop** 2021-10-13 05:26 UTC
